drop table sense;
drop table dict;
drop table kanji;
drop table name;
drop function ends_with_hiragana;
drop function is_katakana;
drop function is_hiragana;
drop function is_kana;
drop function is_kanji;
